<h2></h2>
<table border="1">
    <tr>
    <?php foreach ($headers as $header): ?>
    <th><?php echo $header ?></th>
    <?php endforeach; ?>
    <th><?php echo $this->translate('Actions') ?></th>
    </tr>
    <?php if (count($paginator)): ?>
    <?php foreach ($paginator as $item): ?>
        <tr>
            <?php foreach ($headers as $key => $header): ?>
            <td><?php echo $item[$key] ?></td>
            <?php endforeach; ?>
        <td>
            <a href="<?php echo $this->url(null, array('action' => 'edit', 'id' => $item['id'])) ?>"><?php echo $this->translate('Edit') ?></a>&nbsp;|&nbsp;
            <a href="<?php echo $this->url(null, array('action' => 'delete', 'id' => $item['id'])) ?>"><?php echo $this->translate('Delete') ?></a>
        </td>
        </tr>
        <?php endforeach; ?>
    <?php else: ?>
    <td colspan="<?php echo count($headers) + 1 ?>"><?php echo $this->translate('No data') ?></td>
    <?php endif; ?>
</table>

<?php echo $this->paginationControl($paginator, 'sliding', 'pagination') ?>

<a href="<?php echo $this->url(null, array('action' => 'add')) ?>"><?php echo $this->translate('Add') ?></a>