<h2></h2>
<table>
    <?php foreach ($headers as $header) ?>
    <th><?php echo $header ?></th>
    <?php ?>
    <th><?php echo $this->translate('Actions') ?></th>
<?php if (count($paginator)): ?>
    <?php foreach ($paginator as $item): ?>
        <?php foreach ($item as $key => $value): ?>
        <td><?php echo $value ?></td>
        <?php endforeach; ?>
        <td>
            <a href=""><?php echo $this->translate('edit') ?></a>&nbsp;|&nbsp;
            <a href=""><?php echo $this->translate('delete') ?></a>
        </td>
    <?php endforeach; ?>
<?php else: ?>
    <td colspan="<?php count($headers) + 1 ?>"><?php echo $this->translate('No data') ?></td>
<?php endif; ?>
</table>

<?php echo $this->paginationControl($paginator, 'sliding') ?>

<a href=""><?php echo $this->translate('add') ?></a>