<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle('Планета знаний школа №59')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- Styles -->
    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
                                ->prependStylesheet($this->basePath() . '/css/developer.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.8.0.min.js')
                    ->appendFile($this->basePath() . '/js/placeholder.js') ?>

    <title>Планета знаний школа №59</title>
    <script type="text/javascript">
        $(function(){
            $('input[placeholder], textarea[placeholder]').placeholder();
        });
    </script>

</head>
<body>
<div class="main">
    <!-- header -->
    <div class="floatLeft fullWidth header">
        <!-- header top -->
        <div class="floatLeft fullWidth header-top">
            <div class="floatLeft header-logo"><img src="/images/logo.png" alt="" /></div>
            <div class="floatRight header-login">
                <form action="" class="floatLeft fullWidth">
                    <div class="floatLeft fullWidth header-login-line"><span>Вход в систему:</span></div>
                    <div class="floatLeft fullWidth header-login-line"><input type="text" placeholder="логин"  name="login"/></div>
                    <div class="floatLeft fullWidth header-login-line"><input type="password" placeholder="пароль"  name="password"/></div>
                    <div class="floatLeft fullWidth header-login-line"><a href="/account/registration/" title="Регистрация" target="_self">Регистрация</a></div>
                </form>
            </div>
        </div>
        <!-- /header top -->
        <!-- header bottom -->
        <div class="floatLeft fullWidth header-bottom">
            <div class="floatLeft header-navi">
                <div class="floatLeft header-navi-block"><a href="/" title="Главная страница" target="_self" class="navi1">Главная<br />страница</a></div>
                <div class="floatLeft header-navi-block"><a href="/info/director/" title="Слово директору" target="_self"  class="navi2">Слово<br />директору</a></div>
                <div class="floatLeft header-navi-block"><a href="/info/teacher/" title="Страничка учителя" target="_self"  class="navi3">Страничка<br />учителя</a></div>
                <div class="floatLeft header-navi-block"><a href="/info/class/" title="Классная страничка" target="_self"  class="navi4">Классная<br />страничка</a></div>
                <div class="floatLeft header-navi-block clearRight"><a href="/info/wall/" title="Школьная стена" target="_self"  class="navi5">Школьная<br />стена</a></div>
            </div>
        </div>
        <!-- /header bottom -->
    </div>
    <!-- /header -->
    <!-- content -->
    <div class="content floatLeft">
        <?php echo $this->content; ?>
    </div>
    <!-- /content -->
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>