<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle('Планета знаний школа №59')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- Styles -->
    <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css')
                                ->prependStylesheet($this->basePath() . '/css/developer.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.8.0.min.js')
                    ->appendFile($this->basePath() . '/js/placeholder.js') ?>

    <title>Планета знаний школа №59</title>
    <script type="text/javascript">
        $(function(){
            $('input[placeholder], textarea[placeholder]').placeholder();
        });
    </script>

</head>
<body>
<div class="floatLeft fullWidth main-padder">
<div class="main">
    <!-- header -->
    <div class="floatLeft fullWidth header">
        <!-- header top -->
        <div class="floatLeft fullWidth header-top">
            <div class="floatLeft header-logo"><img src="/images/logo.png" alt="" /></div>
            <div class="floatRight header-login br15">
                <form action="" class="floatLeft fullWidth">
                    <div class="floatLeft fullWidth header-login-line"><span>Вход в систему:</span></div>
                    <div class="floatLeft fullWidth header-login-line"><input type="text" placeholder="логин"  name="login"/></div>
                    <div class="floatLeft fullWidth header-login-line"><input type="password" placeholder="пароль"  name="password"/></div>
                    <div class="floatLeft fullWidth header-login-line"><a href="/account/registration/" title="Регистрация" target="_self">Регистрация</a></div>
                </form>
            </div>
        </div>
        <!-- /header top -->

        <?php $menu = isset($GLOBALS['menu']) ? $GLOBALS['menu'] : array() ?>

        <!-- header bottom -->
        <div class="floatLeft fullWidth header-bottom">
            <div class="floatLeft header-navi">
                <?php $index = 0 ?>
                <?php foreach ($menu as $sort => $item) { ?>
                <div class="floatLeft header-navi-block br5 <?php echo $index == count($menu) - 1 ? 'clearRight': ''; ?>">
                    <a href="<?php echo $item->getHref() ?>" title="<?php echo $item->getTitle() ?>" target="_self"  class="navi navi<?php echo $item->getSort() ?>"><?php echo $item->getTitle() ?></a>
                    <?php $subItems = $item->getSubItems() ?>
                    <?php if (count($subItems) > 0) { ?>
                    <div class="header-navi-menu">
                        <div class="floatLeft header-navi-menu-inner br5">
                            <ul>
                                <?php foreach ($subItems as $subItem) { ?>
                                <li>
                                    <a href="<?php echo $subItem->getHref() ?>" title="<?php echo $subItem->getTitle() ?>" target="_self"><?php echo $subItem->getTitle() ?></a>
                                </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                    <?php } ?>
                </div>
                <?php $index++ ?>
                <?php } ?>
            </div>
        </div>
        <!-- /header bottom -->
    </div>
    <!-- /header -->
    <!-- content -->
    <div class="content floatLeft br5">
        <?php echo $this->content; ?>
    </div>
    <!-- /content -->
</div>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>