<!-- content top -->
<div class="floatLeft fullWidth content-top">
    <div class="floatLeft content-menu">
        <div class="floatLeft content-menu-links">
            <div class="floatLeft fullWidth content-menu-links-line">
                <div class="floatLeft content-menu-links-block" slides="sl1"><span class="current br5">Экскурсия по<br />школе</span></div>
            </div>
            <div class="floatLeft fullWidth content-menu-links-line">
                <div class="floatLeft content-menu-links-block" slides="sl2"><span class="br5">Наши<br />учителя</span></div>
            </div>
            <div class="floatLeft fullWidth content-menu-links-line">
                <div class="floatLeft content-menu-links-block" slides="sl3"><span class="br5">Страницы<br />истории</span></div>
            </div>
            <div class="floatLeft fullWidth content-menu-links-line">
                <div class="floatLeft content-menu-links-block" slides="sl4"><span class="br5">Наши<br />выпускники</span></div>
            </div>
        </div>
        <div class="floatLeft content-menu-slideshow  br10">
            <div class="floatLeft fullWidth slideshow-line" id="sl1">
                <?php $path = $_SERVER['DOCUMENT_ROOT'] . '/images/exhibition/' ?>
                <?php $files = scandir($path) ?>
                <?php foreach ($files as $file) { ?>
                <?php if ($file != '.' && $file != '..') { ?>
                <div class="floatLeft slideshow-block"><img src="/images/exhibition/<?php echo $file ?>" alt="" /></div>
                <?php } ?>
                <?php } ?>
            </div>
            <div class="floatLeft fullWidth slideshow-line" id="sl2">
                <?php $path = $_SERVER['DOCUMENT_ROOT'] . '/images/teachers/' ?>
                <?php $files = scandir($path) ?>
                <?php foreach ($files as $file) { ?>
                <?php if ($file != '.' && $file != '..') { ?>
                    <div class="floatLeft slideshow-block"><img src="/images/teachers/<?php echo $file ?>" alt="" /></div>
                    <?php } ?>
                <?php } ?>
            </div>
            <div class="floatLeft fullWidth slideshow-line" id="sl3">
                <?php $path = $_SERVER['DOCUMENT_ROOT'] . '/images/history/' ?>
                <?php $files = scandir($path) ?>
                <?php foreach ($files as $file) { ?>
                <?php if ($file != '.' && $file != '..') { ?>
                    <div class="floatLeft slideshow-block"><img src="/images/history/<?php echo $file ?>" alt="" /></div>
                    <?php } ?>
                <?php } ?>
            </div>
            <div class="floatLeft fullWidth slideshow-line" id="sl4">
                <?php $path = $_SERVER['DOCUMENT_ROOT'] . '/images/students/' ?>
                <?php $files = scandir($path) ?>
                <?php foreach ($files as $file) { ?>
                <?php if ($file != '.' && $file != '..') { ?>
                    <div class="floatLeft slideshow-block"><img src="/images/students/<?php echo $file ?>" alt="" /></div>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="floatRight content-links  br5">
        <div class="floatLeft fullWidth content-links-header">О школе...</div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/about/" title="Общие сведенья о школе" target="_self">Общие сведения о школе</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/law/" title="Нормативно - правовое обеспечение" target="_self">Нормативно - правовое обеспечение</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/documents/" title="Актуальные документы" target="_self">Актуальные документы</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/public/" title="Публичный доклад" target="_self">Публичный доклад</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/extra-education/" title="Дополнительное образование" target="_self">Дополнительное образование</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/out-class/" title="Внеклассная работа" target="_self">Внеклассная работа</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/ege-gia/" title="Всё о ЕГЭ и ГИА" target="_self">Всё о ЕГЭ и ГИА</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/projects/" title="Наши проекты" target="_self">Наши проекты</a>
        </div>
        <div class="floatLeft fullWidth content-links-line">
            <a href="/info/fgos/" title="ФГОС" target="_self">ФГОС</a>
        </div>
    </div>
</div>
<!-- /content top -->
<!-- content navi -->
<div class="floatLeft fullWidth content-navi">

    <?php $index = 0 ?>
    <?php foreach ($menu as $item) { ?>
    <div class="content-navi-block floatLeft <?php echo $index == count($menu) - 1 ? 'clearRight': ''; ?>">
        <a href="<?php echo $item->getHref() ?>" title="<?php echo $item->getTitle() ?>" target="_self"  class="br5 main"><?php echo $item->getTitle() ?></a>
        <?php $subItems = $item->getSubItems() ?>
        <?php if (count($subItems) > 0) { ?>
        <div class="content-navi-menu">
            <div class="floatLeft content-navi-menu-inner br5">
                <ul>
                    <?php foreach ($subItems as $subItem) { ?>
                    <li>
                        <a href="<?php echo $subItem->getHref() ?>" title="<?php echo $subItem->getTitle() ?>" target="_self"><?php echo $subItem->getTitle() ?></a>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php $index++ ?>
    <?php } ?>

</div>
<!-- /content navi -->
<!-- content main -->
<div class="floatLeft content-main br5">
    <?php if ($page != null): ?>
    <?php echo $page->getText() ?>
    <?php endif; ?>
</div>
<!-- /content main -->

<script>
    $(document).ready(function() {
        /*var lns = $('.slideshow-line');
        for (var i = 0; i < lns.length; i++) {
            var sls = $(lns[i]).find('.slideshow-block');
            for (var j = 0; j < sls.length; j++) {
                $(sls[j]).css('margin-top', '-' + 314*j + 'px');
            }
        }*/

        var index = 1;
        var interval = setInterval(function () {
            var slides = $('.content-menu-links-block span.current').parent().attr('slides');
            $('#' + slides + ' .slideshow-block').fadeOut();
            $($('#' + slides + ' .slideshow-block')[index]).fadeIn();
            index = (index + 1)%$('#' + slides + ' .slideshow-block').length;
        }, 5000)

        $('.content-menu-links-block').bind('click', function () {
            $('.content-menu-links-block span').removeClass('current');
            $($(this).find('span')[0]).addClass('current');
            $('.slideshow-line').hide();
            $('#' + $(this).attr('slides')).show();
            clearInterval(interval);
            interval = setInterval(function () {
                var slides = $('.content-menu-links-block span.current').parent().attr('slides');
                $('#' + slides + ' .slideshow-block').fadeOut();
                $($('#' + slides + ' .slideshow-block')[index]).fadeIn();
                index = (index + 1)%$('#' + slides + ' .slideshow-block').length;
            }, 5000)
        })
    });
</script>